name: Deploy to qualif
run-name: deploy ${{ inputs.commit }} to ${{ inputs.neurinfo && 'neurinfo' || '-' }},${{ inputs.ofsep && 'ofsep' || '-'}} by ${{ inputs.owner }}

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "commit id to be deployed"
        required: true
      owner:
        description: "person who triggered this workflow"
        required: true
      deploy_id:
        description: "unique id for this deployment"
        required: true
      neurinfo:
        type: boolean
        default: false
      ofsep:
        type: boolean
        default: false
      poc-neurinfo:
        type: boolean
        default: false

jobs:
  build:
    uses: ./.github/workflows/docker.yml
    with:
      commit: "${{ inputs.commit }}"

  post_build:
    runs-on: shanoir-deploy
    needs: build
    if: ${{ always() }}
    env:
      DEPLOY_ID: ${{ inputs.DEPLOY_ID }}
    steps:
      - run: sh /run/github-runner/deploy-shanoir post_build ${{ needs.build.result }}

  deploy-neurinfo:
    if: ${{ inputs.neurinfo }}
    needs: [ build, post_build ]
    runs-on: shanoir-deploy
    env:
      DEPLOY_ID: ${{ inputs.DEPLOY_ID }}
    steps:
      - run: sh /run/github-runner/deploy-shanoir neurinfo

  deploy-ofsep:
    if: ${{ inputs.ofsep }}
    needs: [ build, post_build ]
    runs-on: shanoir-deploy
    env:
      DEPLOY_ID: ${{ inputs.DEPLOY_ID }}
    steps:
      - run: sh /run/github-runner/deploy-shanoir ofsep

  deploy-poc-neurinfo:
    if: ${{ inputs.poc-neurinfo }}
    needs: [ build, post_build ]
    runs-on: shanoir-deploy
    env:
      DEPLOY_ID: ${{ inputs.DEPLOY_ID }}
    steps:
      - run: sh /run/github-runner/deploy-shanoir poc-neurinfo
