name: Deploy to qualif
run-name: deploy ${{ inputs.commit }} to [${{ inputs.neurinfo && 'neurinfo' || '' }} ${{ inputs.ofsep && 'ofsep' || ''}} ${{ inputs.poc-neurinfo && 'poc-neurinfo' || ''}}] by ${{ inputs.owner }}

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "commit id to be deployed"
        required: true
      owner:
        description: "person who triggered this workflow"
        required: true
      deploy_id:
        description: "unique id for this deployment"
        required: true
      neurinfo:
        type: boolean
        default: false
      ofsep:
        type: boolean
        default: false
      poc-neurinfo:
        type: boolean
        default: false
      runner:
        description: "target runner for the deployment"
        required: true
        type: choice
        options: [ shanoir-deploy, shanoir-2016, eskemm-poc ] # TODO: cleanup

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      sha:     ${{ steps.prepare.outputs.sha }}
      status:  ${{ steps.prepare.outputs.status }}
      targets: ${{ steps.prepare.outputs.targets }}
    permissions:
      packages: read
    steps:
      - name: prepare deployment (resolve git commit, query registry, identify targets)
        id: prepare 
        env:
          INPUTS: ${{ toJSON(inputs) }}
        shell: python
        run: |
          import json, os, pathlib, re, requests
          from urllib.parse import quote_plus

          def get(endpoint: str) -> requests.Response:
            return requests.get(f"${{ github.api_url }}{endpoint}", headers={
                "Authorization": f"Bearer ${{ github.token }}",
                "X-GitHub-Api-Version": "2022-11-28",
                })

          def resolve_commit(commit: str) -> str:
            repo = "/repos/${{ github.repository }}"
            
            # match by tag/branch
            for prefix in ("", "tags/", "heads/"):
              rep = get(f"{repo}/git/ref/{quote_plus(prefix + commit)}")
              if rep.ok:
                js = rep.json()
                assert js["object"]["type"] == "commit", "intermediate objects not supported (eg: tag objects)"
                return js["object"]["sha"]

            # match by commit
            if re.fullmatch(f"[0-9a-f]+", commit):
              # match by commit
              rep = get(f"{repo}/commits/{quote_plus(commit)}")
              if rep.ok:
                return rep.json()["sha"]

            if rep.status_code == 404:
              raise ValueError(f"unknown git commit: {commit}")
            rep.raise_for_status()

          def check_docker_images(sha: str) -> str:
            # FIXME: nifti-conversion will not be found
            #  -> should run push_to_registry even if this job fails (is that possible?)
            for image in ["database"]:
              rep = get(f"/users/a-ba/packages/container/shanoir-ng%2F{image}/versions")
              if rep.ok:
                if any(sha in version["metadata"]["container"]["tags"] for version in rep.json()):
                  continue
              elif rep.status_code != 404:
                  rep.raise_for_status()
              print(f"image shanoir-ng/{image}:{sha} not yet built and pushed to the registry")
              return ""
            return "ok"

          inputs = json.loads(os.environ["INPUTS"])
          print("inputs:", inputs)
          print("git commit to be deployed: {inputs['commit']}")
          sha = resolve_commit(inputs['commit'])
          print(f"  --> resolved to: {sha}")
          status = check_docker_images(sha)
          if status:
            print("docker images already built")
          targets = [t for t in ("neurinfo", "ofsep", "poc-neurinfo") if inputs[t]]
          print(f"sha={sha}\nstatus={status}\ntargets={json.dumps(targets)}\n")
          pathlib.Path(os.environ["GITHUB_OUTPUT"]).write_text(
            f"sha={sha}\nstatus={status}\ntargets={json.dumps(targets)}\n")

  build:
    needs: prepare
    if: needs.prepare.outputs.status != 'ok'
    uses: ./.github/workflows/docker.yml
    with:
      sha: "${{ needs.prepare.outputs.sha }}"

  post_build:
    runs-on: ${{ inputs.runner }}
    needs: prepare, build
    if: ${{ always() }}
    env:
      DEPLOY_ID: ${{ inputs.DEPLOY_ID }}
    steps:
      - run: sh /run/github-runner/deploy-shanoir post_build ${{ needs.build.result }}
      - run: sh echo '${{ needs.prepare.outputs.targets }}'


  deploy:
    needs: [ prepare, post_build ]
    runs-on: ${{ inputs.runner }}
    env:
      DEPLOY_ID: ${{ inputs.DEPLOY_ID }}
    strategy:
      matrix:
        targets: ${{ fromJSON(needs.prepare.outputs.targets) }}
    steps:
      - run: sh /run/github-runner/deploy-shanoir ${{ matrix.target }}

#  deploy-neurinfo:
#    if: ${{ inputs.neurinfo }}
#    needs: [ build, post_build ]
#    runs-on: shanoir-deploy
#    env:
#      DEPLOY_ID: ${{ inputs.DEPLOY_ID }}
#    steps:
#      - run: sh /run/github-runner/deploy-shanoir neurinfo
#
#  deploy-ofsep:
#    if: ${{ inputs.ofsep }}
#    needs: [ build, post_build ]
#    runs-on: shanoir-deploy
#    env:
#      DEPLOY_ID: ${{ inputs.DEPLOY_ID }}
#    steps:
#      - run: sh /run/github-runner/deploy-shanoir ofsep
#
#  deploy-poc-neurinfo:
#    if: ${{ inputs.poc-neurinfo }}
#    needs: [ build, post_build ]
#    runs-on: shanoir-deploy
#    env:
#      DEPLOY_ID: ${{ inputs.DEPLOY_ID }}
#    steps:
#      - run: sh /run/github-runner/deploy-shanoir poc-neurinfo
