name: Deploy to qualif
run-name: ${{ inputs.description }}

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "commit id to be deployed"
        required: true
      description:
        description: "description of this workflow run"
        required: true
      deploy_id:
        description: "unique id for this deployment"
        required: true
      neurinfo:
        type: boolean
        required: true
      ofsep:
        type: boolean
        required: true

jobs:
  build_docker_images:
    uses: ./.github/workflows/docker.yml
    with:
      commit: "${{ inputs.commit }}"
  
  deploy:
    runs-on: ubuntu-latest
    environment: qualif
    env:
      url:        ${{ secrets.SHANOIR_DEPLOY_URL }}
      token:      ${{ secrets.SHANOIR_DEPLOY_TOKEN }}
      deploy_id:  ${{ inputs.deploy_id }}
    steps:
      - env:
          instance: neurinfo-qualif
        name: "deploy to ${{ env.instance }}"
        run: |
          base64 <<EOF
          curl --fail --no-progress-meter -H "Authorization: Token $token" -d "deploy_id=$deploy_id" -d "instance=$instance" -X POST -- "$url"
          EOF
      - env:
          instance: ofsep-qualif
        name: "deploy to ${{ env.instance }}"
        run: |
          curl --fail --no-progress-meter -H "Authorization: Token $token" -d "deploy_id=$deploy_id" -d "instance=$instance" -X POST -- "$url"
