name: Deploy to qualif
run-name: deploy ${{ inputs.commit }} to ${{ inputs.neurinfo && 'neurinfo' || '-' }},${{ inputs.ofsep && 'ofsep' || '-'}} by ${{ inputs.owner }}

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "commit id to be deployed"
        required: true
      owner:
        description: "person who triggered this workflow"
        required: true
      deploy_id:
        description: "unique id for this deployment"
        required: true
      neurinfo:
        type: boolean
        required: true
      ofsep:
        type: boolean
        required: true

jobs:
  build:
    uses: ./.github/workflows/docker.yml
    with:
      commit: "${{ inputs.commit }}"

  deploy-neurinfo:
    if: ${{ inputs.neurinfo }}
    needs: build
    runs-on: shanoir-deploy
    env:
      DEPLOY_ID: ${{ inputs.DEPLOY_ID }}
    steps:
      - name: "deploy commit ${{ needs.build.outputs.sha }}"
        run: /run/github-runner/deploy-shanoir "$DEPLOY_ID" neurinfo

  deploy-ofsep:
    if: ${{ inputs.ofsep }}
    needs: build
    runs-on: shanoir-deploy
    env:
      DEPLOY_ID: ${{ inputs.DEPLOY_ID }}
    steps:
      - name: "deploy commit ${{ needs.build.outputs.sha }}"
        run: /run/github-runner/deploy-shanoir "$DEPLOY_ID" ofsep

